# Generated by Django 2.0.7 on 2018-08-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default='0.0.0.0', max_length=200, null=True)),
                ('info', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('hostname', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('able_to_ping', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('able_to_login', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('physical_or_vm', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('issues', models.CharField(blank=True, default='None', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default='0.0.0.0', max_length=200, null=True)),
                ('info', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('hostname', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('able_to_ping', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('able_to_login', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('physical_or_vm', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('issues', models.CharField(blank=True, default='None', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default='0.0.0.0', max_length=200, null=True)),
                ('info', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('hostname', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('able_to_ping', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('able_to_login', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('physical_or_vm', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('issues', models.CharField(blank=True, default='None', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Windows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, default='0.0.0.0', max_length=200, null=True)),
                ('info', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('hostname', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('able_to_ping', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('able_to_login', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('physical_or_vm', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('issues', models.CharField(blank=True, default='None', max_length=200, null=True)),
            ],
        ),
    ]
