# Generated by Django 2.0.7 on 2018-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linux',
            name='id',
            field=models.DecimalField(blank=True, decimal_places=5, default=-1, max_digits=5, primary_key=True, serialize=False),
        ),
    ]
