# Generated by Django 2.0.7 on 2018-08-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180805_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linux',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
