# Generated by Django 2.0.5 on 2018-08-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180805_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='linux',
            name='type',
            field=models.CharField(blank=True, default='NaN', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='type',
            field=models.CharField(blank=True, default='NaN', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, default='NaN', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='windows',
            name='type',
            field=models.CharField(blank=True, default='NaN', max_length=200, null=True),
        ),
    ]
