# Generated by Django 2.0.5 on 2018-08-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180807_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='linux',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='network',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='windows',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
