# Generated by Django 2.0.5 on 2018-08-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180808_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linux',
            name='status',
            field=models.CharField(default='False', max_length=6),
        ),
        migrations.AlterField(
            model_name='network',
            name='status',
            field=models.CharField(default='False', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='False', max_length=6),
        ),
        migrations.AlterField(
            model_name='windows',
            name='status',
            field=models.CharField(default='False', max_length=6),
        ),
    ]
